# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoAppSoTay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'mailcore2-ios'
  # Pods for DemoAppSoTay

  target 'DemoAppSoTay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoAppSoTayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'DemoAppSoTay-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for DemoAppSoTay-tvOS

#   target 'DemoAppSoTay-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
